### ISSUE TITLE
yiimp mining pool functions

### ISSUE THREAD

**Issue by ZhenyuChenIan** [xaya/xaya#80] opened 2019-01-05 05:01 UTC
We are trying to setup a yiimp mining pool to mine CHI(Xaya), 

but some functions is not found (returns "error -32601: method not found"),

so we looked into the pool's codes, found the pool can not work without 4 functions, which is missing in xaya 1.1.
the 4 functions are: 
1. getinfo (Returns an object containing various state info.)
2. getaccountaddress (Returns the current bitcoin address for receiving payments to this account. If <account> does not exist, it will be created along with an associated new address that will be returned.)
3. listaccounts (Returns Object that has account names as keys, account balances as values.)
4. move  (Move from one account in your wallet to another)
they are usually inherited from bitcoin and most coins have them, but we could not found in xaya 1.1

we are using ubuntu18.04 and pool is yiimp which based on yaamp, a common used pool.

**Comment by domob1812** [comment] 2019-01-05 11:56
Those functions have been deprecated and later removed in Bitcoin Core for a long time, please replace them accordingly.

1) `getinfo` should be replaced with `getnetworkinfo`, `getwalletinfo` and `getmininginfo`.
2) `getaccountaddress` should be replaced with `getnewaddress` (and setting a label).
3) `listaccounts` should be replaced with `listlabels`.
4) `move` and internal accounting (other than labeling addresses) is no longer supported, since it never really worked as intended anyway.  Why would a pool need that?

**Comment by ZhenyuChenIan** [comment] 2019-01-05 14:30
hi domob, thanks for your reply! indeed those functions are expired, but most pool codes are finished before 2017 with old functions, while many coins inherited old bitcoin codes so these two old things works fine together and widely... 
so from tech perspective the old functions has no value, but from real business perspective, they mean compatible to most exising mainstream pools (maybe 85%+), maybe good for xaya's widely adoption.

**Comment by domob1812** [comment] 2019-01-06 09:34
I understand that - but I'm afraid we are still not going to support them, since we try to follow upstream Bitcoin code as closely as possible.  (And yes, I know that 99.9% of alts out there use very outdated Bitcoin code and never update it - but that is not something we should immitate.)

**Comment by xaya** [comment] 2019-01-09 21:51
@ZhenyuChenIan 
are there any other mining pool softwares you can use?

**Comment by domob1812** [comment] 2019-05-03 12:22
Closing this, as we are not going to add back the old functions.  Instead, pool software should be fixed - that will be needed anyway at some point in the future to support new versions of Bitcoin itself as well.

**Closed by domob1812** 2019-05-03 12:22 UTC
